### PR TITLE
finished all unit tests with loc and iloc implementation except colon

### PR DESCRIPTION
**Pull request by nickjsr**
As titled. I added tests for setitem, deepcopy, and arrange. I also implemented loc and iloc.
One big issue I faced is the loc and iloc cannot support slices, i.e. those have colon within pass-in parameters. Our examples inside example.ipynb need loc with colon. 
Please help me if you know how to put colon into pass-in parameters without raising syntax error
Thanks

### CODE REVIEW

**Review by ccharp — CHANGES_REQUESTED** [review]
I'm not sure that a one-to-one mapping onto loc and iloc is the way to go here. We want to provide an dplyr-like interface, not duplicate Pandas. The dplyr way of doing this is with slice:
https://dplyr.tidyverse.org/reference/slice.html

The user can do this:
```
df + slice(range(i, k))
```
And I'm not sure we need loc. Isn't this functionality already essentially provided via select? 

What do you think? 

Also, make sure to return a DplyFrame and not a pandas Dataframe in your pipeline methods.

**Comment by nickjsr** [comment]
Thank you very much Corbin! Your ideas are amazing. I will follow your suggestions and change to slice later today

**Comment by nickjsr** [comment]
Finished edits.
iloc is renamed to slice
loc is kept and renamed because currently we do not support select subset of dataframe based on row/index names

**Comment by nickjsr** [comment]
@ccharp @MatthewChau99 
This branch does not contain loc and slice right now because this part has not been reviewed by all of you. 
Previous pull requests were based on old commits. I manually fixed them.
I will open another branch for loc and slice. Please pull from the main branch to get the most updated code.

**Pull request merged**
