### PR TITLE
Implement 'side_effect' pipeline method

### LINKED ISSUE #3: Design pipeline plotting interface
This seems more complex than implementing straightforward pipeline methods (like query or apply). What plots should be accessible? 

Maybe we just have a function that takes another function that does something arbitrary, like plot with seaborn, e.g.

dplyFrame + query("query string") + side_effect(lambda df: do_plotting...)

### PR DESCRIPTION
**Pull request by ccharp**
Resolves #3

### CODE REVIEW

**Review by nickjsr — APPROVED** [review]

**Comment by ccharp** [comment]
@MatthewChau99 could I please get a review on this?

**Comment by MatthewChau99** [comment]
Yup looking at it right now!

**Comment by MatthewChau99** [comment]
Have you tried other functions, besides printing it? How about functions like adding 1 to some of the numerical columns?

**Comment by MatthewChau99** [comment]
Okay I added a couple tests on my side and they worked.

**Review by MatthewChau99 — APPROVED** [review]

**Comment by nickjsr** [comment]
Matthew what local tests did you write? Maybe we can add them before merging to main

**Comment by nickjsr** [comment]
Matthew what local tests did you write? I think we can include them

**Pull request merged**
