### PR TITLE
Readme updates

### LINKED ISSUE #54: Polish README
Shared doc link: https://docs.google.com/document/d/1TMQDz056_rTYxK9tnxopQ4px4kkeRZ0s0vYKtnRsxp8/edit
I believe we need:
1. project organization tree
2. one sentence referring usage to example folder, and pipeline methods explanation with moderate details
3. one sentence explaining GitHub action building pass instead of travis-CI
4. one sentence mentioning using pylint instead of flake8 to check style
5. one sample output in the end extracted from examples.ipynb

### PR DESCRIPTION
**Pull request by ccharp**

### CODE REVIEW

**Review by nickjsr — CHANGES_REQUESTED** [review]
Please remember to pull first since I committed some changes online
We may need to include a figure that contains sample output. I put one in example folder.

**Review by nickjsr — COMMENTED** [review]
I believe we need to introduce pipeline methods and include a sample output in README, but please ignore my previous change requested

**Review by nickjsr — APPROVED** [review]
See my comments above. Thanks

**Comment by ccharp** [comment]
@nickjsr unless there are merge conflicts, you do not need to manually enter changes from other branches (including main). Git will reconcile differences automatically (unless it can't, in which case we'd see a merge conflict). 

The latest push includes API documentation generated from our inlined doc strings. The README now links to that documentation. 

I do not think sample output in README.md is necessary.

**Comment by nickjsr** [comment]
> @nickjsr unless there are merge conflicts, you do not need to manually enter changes from other branches (including main). Git will reconcile differences automatically (unless it can't, in which case we'd see a merge conflict) when this branch is merged into main.
> 
> The latest push includes API documentation generated from our inlined doc strings. The README now links to that documentation.
> 
> I do not think sample output in README.md is necessary.

Thank you very much for your reminder Corbin! You are absolutely correct. The first two commits deal with a merge conflict which is caused by examples.ipynb. The file inside main is correct but the file inside here was not correct, so I manually entered changes. The third one fixes the broken build passing. Now let me delete the output picture. Thanks!

**Review by MatthewChau99 — APPROVED** [review]

**Pull request merged**
