### PR TITLE
Check null

### PR DESCRIPTION
**Pull request by nickjsr**
Finished check_null. Support checking dataframe or a column of a dataframe if there exists a null value, how many null values

### CODE REVIEW

**Comment by ccharp** [comment]
@nickjsr I think your text editor is automatically changing all single quotes to double quotes. Could you please disable that? It bloats the diff. 

Otherwise, this looks pretty good. The only thing I'd ask about now is error handling: the rest of our API largely delegates error handling to Pandas. What does Pandas do if a column is incorrectly specified? Is it necessary that we detect that and throw the error instead of Pandas?

**Comment by nickjsr** [comment]
@ccharp Sorry I have no idea on converting single quotes to double quotes. After some searches, I only see how to disable autocomplete pairs of quotes. I use sublime text 3 on PC. 
Regarding error handling, I am sure that my types of errors like keyerror and valueerror are consistent with pandas errors.

**Comment by nickjsr** [comment]
Also, do you all think check_null_any and check_null_total are necessary? I can delete them

**Comment by nickjsr** [comment]
@ccharp I don't think the conversion is made by my text editor. Maybe because of pre-commit. It reformatted my code every time I tried to commit

**Comment by ccharp** [comment]
> Also, do you all think check_null_any and check_null_total are necessary? I can delete them

I don't think `check_null_any` is necessary if we have `check_null_total`. You may also rename it to `count_nulls` or similar.

**Comment by ccharp** [comment]
> Regarding error handling, I am sure that my types of errors like keyerror and valueerror are consistent with pandas errors.

My point is that we should let Pandas report problems if there are any. Otherwise, we'd need to implement error handling for our entire API to stay consistent with ourselves.

**Review by ccharp — APPROVED** [review]

**Pull request merged**
